### ISSUE TITLE
ТЗ

### ISSUE THREAD

**Issue by yorsenai** [perfomanceartist/AIDemonstrationStand#1]
######## ОБЩЕЕ #########
- [x] Кнопка Далее на Завершение
- [x] Привести Гуи в порядок (размеры и расположения)
- [x] Перегнать готовые модули
- [x] В DatasetPoisoning (StopSign) подписать диалоговое окно как датасет обучения ИИ
- [x] В DatasetPoisoning (StopSign) также в диалоговом окне при атаках нужно обвести отравленную картинку красным
- [x] Добавить дефолтное изображение (лого ИКиЗИ), все подгрузки изображений делать через try-except, при except - подгружать дефолтное изображение
- [x] Создать модуль Исследования Членства и еще 2 модуля @perfomanceartist 
- [x] !! Решить проблему с выводом в конце демонстрации (Вывод того, что в итоге выдал ИИ, сейчас этого просто нет)
- [x] Либо расписать для каждой сети соотношения объектов и весов 👎, либо полностью убрать упоминание этого из текстов 👍 

######## ТЕКСТЫ #########
- [x] Переписать тексты OnePixelAttack и DatasetPoisoning под другие архитектуры ИИ (сухо и научно!!)
- [x] Привести тексты к научному виду (везде использовать термин "Классификация входных данных")
- [x] Сократить тексты чтоб без скроллбаров
- [x] Вывести все тексты с 0х слайдов в описания, сами слайды удалить
- [x]  Убрать упоминания CIFAR10, STATE OF ART и параметра CONFIDENCE

####### README ########
- [x] Начать вести учет используемых библиотек

**Comment by perfomanceartist** [comment]
- [x] ⭐Краткое описание стенда (программные модули, используемые библиотеки с указанием цели использования)
- [x]  полностью расписать сценарий "DeepFooll" (атака на CNN). Тем более уже много расписано, многое есть. Нужно вычитать текст. Чтобы мы посмотрели, осознали +-. Чтобы потом распространять/масштабировать на оставшиеся 5 сценариев.
- [x] Описание категорий
- [x] Убрать кнопку "начать демонстрацию" и параметры
- [x] Иконка программы
- [x] Картинки в STOP SIGN поехали

**Comment by yorsenai** [comment]
💯
